# Title of your blog; shows in the header
name: "LuaFormatter-Report | GSoC 2020"

# Description of your content (will only be used on Google Search)
description: "Project Report "

# Your name. Will show in your footer + sidebar
author: "Ankit Karan"
mentor: "Pedro Tammela"

url: "http://karanankit01.github.io"
baseurl: "/LuaFormatter-Report"

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "Software Developer @LabLua | Google Summer of Code 2020"
mentor-bio: "Mentor @LabLua | Google Summer of Code 2020"

# Social Accounts (mine, as placeholders)

project: LuaFormatter/tree/master
twitter: baba_gyanee
github: karanankit01
linkedin: ankit-karan-47904b182
instagram: _i_m_ank_

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: karanankit01.github.io
ga_tracking_id: UA-47727049-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
